# Generated by Django 4.0.6 on 2022-07-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='users/default-pfp.jpg', upload_to='users/upload'),
        ),
    ]
