# Generated by Django 4.0.6 on 2022-07-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='users/default-pfp.jpg', upload_to='users/profile-pics/'),
        ),
    ]
