# Generated by Django 4.0.6 on 2022-07-13 12:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='users/default-pfp.jpg', upload_to=users.models.pfpUpload),
        ),
    ]
