# Generated by Django 4.0.6 on 2022-07-10 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='4 digit code. Last 2 digits of academic year followed by 2 digits of semester number. Eg- 2101', max_length=4)),
                ('course_code', models.CharField(help_text='Eg- APL100, MCP101', max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('coordinator', models.ForeignKey(blank=True, limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_coordinating', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 3}, related_name='courses_studying', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 2}, related_name='courses_teaching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
