# Generated by Django 4.0.6 on 2022-07-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('grade',)},
        ),
    ]
