# Generated by Django 4.0.6 on 2022-07-15 16:05

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_coursesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('time_last_modified', models.DateTimeField(auto_now=True)),
                ('access', models.PositiveSmallIntegerField(choices=[(1, 'Author Only'), (2, 'Teachers Only'), (3, 'Everyone')], default=1)),
                ('display_text', models.CharField(blank=True, max_length=256)),
                ('icon', models.ImageField(default='course/icons/default.jpg', upload_to='')),
                ('url', models.URLField(blank=True, max_length=512)),
                ('author', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.item')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=course.models.Document.material_upload)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.item')),
            ],
        ),
    ]
