# Generated by Django 4.0.6 on 2022-07-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
