# Generated by Django 4.0.6 on 2022-07-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_item_link_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='display_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
