# Generated by Django 4.0.6 on 2022-07-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_item_alter_coursesection_title_link_item_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.item')),
            ],
        ),
    ]
