# Generated by Django 4.0.6 on 2022-08-03 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_remove_page_title_alter_coursesection_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_time', models.DateTimeField()),
                ('late_due_time', models.DateTimeField(blank=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.item')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'No Submission'), (2, 'Ungraded'), (3, 'Graded')], default=1)),
                ('grade', models.FloatField(blank=True)),
                ('grading_time', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment')),
                ('grader', models.ForeignKey(blank=True, limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_graded', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
