# Generated by Django 4.0.6 on 2022-08-06 10:50

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_submission_submitted_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=course.models.Submission.submission_upload),
        ),
    ]
