# Generated by Django 4.0.6 on 2022-08-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_submission_grader_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_grade',
            field=models.FloatField(default=100.0),
        ),
    ]
