# Generated by Django 4.0.6 on 2022-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_assignment_max_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grading_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
