# Generated by Django 4.0.6 on 2022-08-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_submission_grading_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
