# Generated by Django 4.0.6 on 2022-08-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_delete_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
